name: Deploy static website to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ConsultingReimaginedai'  # 👈 Make sure this matches your Azure Web App name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # 👈 Add this in your repo’s GitHub secrets
          package: .

          